{
 "title": "Rate Limiter Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Requests Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rate_limiter_allowed_total[30s])",
     "legendFormat": "Allowed/s"
    },
    {
     "expr": "rate(rate_limiter_rejected_total[30s])",
     "legendFormat": "Rejected/s"
    }
   ]
  },
  {
   "title": "Allowed vs Rejected",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate_limiter_allowed_total", "legendFormat": "Allowed" },
    { "expr": "rate_limiter_rejected_total", "legendFormat": "Rejected" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate_limiter_processed_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "targets": [
    { "expr": "rate_limiter_active_users", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Max Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "rate_limiter_latency_max_ms", "legendFormat": "Max" }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "Threads" }
   ]
  },
  {
   "title": "Avg Processing Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "rate_limiter_latency_avg_ms", "legendFormat": "Avg Latency" }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "Used" },
    { "expr": "jvm_memory_max_bytes", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Rate Limiter Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"rate-limiter-rate-limiter-1\"}"
    }
   ]
  }
 ]
}